### ISSUE TITLE
First Launch

### ISSUE THREAD

**Issue by wcosmas** [Jacse/react-native-app-intro-slider#120]
How should i make the intro pages to appear only on first launch??

**Comment by Jacse** [comment]
Basically what you need is some sort of persistent storage where you can check if the app has been opened before. One way is to set some value to true in AsyncStorage on first launch. If a key (e.g. 'hasBeenOpened') doesn't exist, if is the first time the app is launched, otherwise it is not.

You can check #18 to see an example of how to conditionally show the intro pages.

Since this is not an issue with the library I'm going to close it. If you need general help with React Native I would suggest StackOverflow.
