### ISSUE TITLE
One custom item while the others are default

### ISSUE THREAD

**Issue by jcomplex** [Jacse/react-native-app-intro-slider#35]
I am trying to have one slide that does not have an image (title and text are center aligned on the slide) but by default there is space in the center for an image component.  Is there a way I can render a custom first slide?

**Comment by Jacse** [comment]
Instead of hacky workaraounds I'd suggest to implement a custom `renderSlide`-function. If you take a look at [the default one](https://github.com/Jacse/react-native-app-intro-slider/blob/master/DefaultSlide.js) you'll see that it's actually very simple. That way you are in complete control. Id suggest doing the following:
```js
  renderSlide={(props) => {
    const style = {
      backgroundColor: props.backgroundColor,
      paddingTop: props.topSpacer,
      paddingBottom: props.bottomSpacer,
      width: props.width,
      height: props.height,
    }
    return (
      <View style={[styles.slideContent, style]}>
        <Text style={styles.title}>{props.title}</Text>
        {props.image && <Image source={props.image} style={styles.imageStyle} />}
        <Text style={styles.text}>{props.text}</Text>
      </View>
    );
  }}
```

If you want you can include the default styles or tweak them to your needs:
```js
const styles = StyleSheet.create({
  slideContent: {
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  text: {
    color: 'rgba(255, 255, 255, .7)',
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '300',
    paddingHorizontal: 16,
  },
  title: {
    fontSize: 26,
    color: 'rgba(255, 255, 255, .7)',
    fontWeight: '300',
    paddingHorizontal: 16,
  },
  imageStyle: // whatever
});
```

**Comment by Jacse** [comment]
Let me know if you run into any issues.

**Comment by jcomplex** [comment]
@Jacse thanks I will try this.
